[package]
name = "libmctp"
repository = "https://github.com/?/?"
version = "0.1.0"
authors = ["Alistair Francis <alistair.francis@wdc.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
bitfield = "0.13.2"
smbus-pec = "0.1.0"
